### ISSUE TITLE
Issue in # Atomic Test 11 - T1555.003 - Dump Credentials using Lazagne

### ISSUE THREAD

**Issue by JohnRyk** [skandler/simulate-akira#1]
Invoke-AtomicTest T1555.003 -TestNumber 9  - (LaZagne.py - Dump Credentials from Firefox Browser) this test is for Linux

Should be change it to Invoke-AtomicTest T1555.003 -TestNumber 3 - (LaZagne - Credentials from Browser) ?

**Comment by skandler** [comment]
Thank you John for pointing that out. I have corrected it.
